import "styles/globals.css";
import { Rubik } from "next/font/google";

import Layout from "components/layout/Layout";

import { StateProvider } from "context/context";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Menu app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={rubik.style}>
      <StateProvider>
        <body
          className={` bg-pepperTexture bg-contain relative flex items-start justify-center flex-col w-full`}
        >
          
          <Layout>{children}</Layout>
        </body>
      </StateProvider>
    </html>
  );
}
